---
- name: deploy js application
  hosts: all
  #become: yes
  tasks:
  - name: run container
    docker_container:
      name: webjssrv01
      image: "{{ image }}"
      ports: "{{ port }}":8080
      state: started